### ISSUE TITLE
package name does not match README

### ISSUE THREAD

**Issue by poblin-orange** [hybris/bosh-init-deployment-resource#2]
Hello, trying use bosh release with our concourse deployment.
Noticed the package for image tag is wrong in README
Had to use bosh-init package for the ressource to run on concourse.

```
    - type: bosh-init-deployment
      image: /var/vcap/packages/bosh-init
```

**Comment by robdimsdale** [comment]
+1

I opened a PR for this at https://github.com/hybris/bosh-init-deployment-resource-boshrelease/pull/1

**Comment by joek** [comment]
PR is merged.

**Comment by poblin-orange** [comment]
thks :-)
